# Generated by Django 5.0.2 on 2024-03-26 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_usuario_email_alter_usuario_numero_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_cuenta',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
