# Generated by Django 5.0.2 on 2024-03-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_usuario_numero_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
